version: '3'
services:
  sheltershare:
    build:
      context: ./
      dockerfile: ./docker/sheltershare/Dockerfile
    environment:
      - TZ=Europe/Berlin
      - DEBUG=$DEBUG
    container_name: "sheltershare"
    ports:
      - 1972:1972
      - 52773:52773
      - 8000:8000
      - 8001:8001
    volumes:
      - /tmp:/tmp

