version: '3'
services:
  iris:
    build: docker/iris
    container_name: "iris"
    ports:
      - 1972:1972
      - 52773:52773
    volumes:
      - /tmp:/tmp
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
  sheltershare:
    build:
      context: ./
      dockerfile: ./docker/sheltershare/Dockerfile
    environment:
      - TZ=Europe/Berlin
      - DEBUG=$DEBUG
    container_name: "sheltershare"
    command: >
      sh -c "sleep 10
             python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py makemigrations shshapp&&
             python manage.py migrate shshapp &&
             python manage.py loaddata shshapp/fixtures/* &&
             uvicorn shshproj.asgi:application --reload --host 0.0.0.0 --port 8000 --workers 4 --log-level debug"
    ports:
      - "8000:8000"
    volumes:
      - ./shshproj:/code
      - ./static:/storage/static
      - /tmp:/tmp
    links:
      - iris:iris
  nginx:
    restart: always
    build: docker/nginx
    container_name: "nginx"
    ports:
      - "8080:8080"
    volumes:
      - /tmp/sheltershare/static:/static
    links:
      - sheltershare:sheltershare